### ISSUE TITLE
Look good New update UI

### ISSUE THREAD

**Issue by nidz-the-fact** [chaindrop-raas/oni-bridge#3] opened 2024-05-22 15:45 UTC
**Thank you** for updating the new UI and sharing.

One more thing, I'm having a bit of a problem with showing the Native balance on L2. When I start ERC20 L1 <-> Native L2, when running local it shows the balance and works. But when I try to run it on the website Unable to display Native L2 balance, not sure what's causing it. https://github.com/nidz-the-fact/custom-gas-token-bridge

_Here is more information. **Thank you again**_ 👇
![image](https://github.com/JoinOrigami/custom-gas-token-bridge/assets/106298826/1092a09b-671e-415c-8ca0-9acb743c7cbd)
![image](https://github.com/JoinOrigami/custom-gas-token-bridge/assets/106298826/4f67722e-2a36-4fb2-a7c5-e48315bbea10)

For `OP Stack CustomGas ERC20` <-> Native L2 deployments

**Comment by mrmemes-eth** [comment] 2024-05-22 16:21
The most likely cause is that an environment variable (likely the RPC url) in the deployed environment isn't set, isn't set correctly or is set to an inaccessible URL.

There were some minor changes that may improve the error information you get back if you updated to the latest `main` commit (this looks like it's from before the new UI was merged).

**Comment by nidz-the-fact** [comment] 2024-05-22 17:09
> The most likely cause is that an environment variable (likely the RPC url) in the deployed environment isn't set, isn't set correctly or is set to an inaccessible URL.
> 
> There were some minor changes that may improve the error information you get back if you updated to the latest `main` commit (this looks like it's from before the new UI was merged).

Yes, the latest repo also has this problem. I have verified rpc correctly. Still encountering this problem only on the website. _You can test it._

**Comment by mrmemes-eth** [comment] 2024-05-29 21:28
I'm still unable to reproduce. Do you have any additional details for how to see it? If you can provide a .env that shows the issue, that would be helpful.

**Comment by nidz-the-fact** [comment] 2024-05-30 11:34
> I'm still unable to reproduce. Do you have any additional details for how to see it? If you can provide a .env that shows the issue, that would be helpful.

This 👇
```
# The address of the token on the parent chain that will be used as the gas token on the rollup - does not need to be on an L1
VITE_L1_CUSTOM_GAS_TOKEN_ADDRESS=0x39BE211eAb65e05ba98af949d3e16F7A1683d94E
# The address of the "L1" (parent) contract that will be used to deposit/withdraw funds from the rollup
VITE_L1_OPTIMISM_PORTAL_ADDRESS=0x0d605bb7d4FB586eAB750205F5247825F4D8AF4B
# URL of the official branding icon for the "L2" (rollup) chain
VITE_L2_OUTPUT_ORACLE_ADDRESS=0x74Ad6E0FB793eB5e6c1ff1225B03F5C5fFB7EF0c

# The name of the gas token
VITE_L1_CUSTOM_GAS_TOKEN_NAME=L1Token
# The symbol of the gas token
VITE_L1_CUSTOM_GAS_TOKEN_SYMBOL=L1TKN
# The number of decimals the gas token has - this _must_ be 18 per OP Stack requirements
VITE_L1_CUSTOM_GAS_TOKEN_DECIMALS=18

# chain ID of the "L1" (parent) chain
VITE_L1_CHAIN_ID=88991
# URL of the official branding icon for the "L1" (parent) chain
VITE_L1_ICON_URL=https://avatars.githubusercontent.com/u/121443205?s=200&v=4
# Background color for the icon of the "L1" (parent) chain
VITE_L1_ICON_BACKGROUND_COLOR="#000"

# chain ID of the "L2" (rollup) chain
VITE_L2_CHAIN_ID=7001
# name of the "L2" (rollup) chain
VITE_L2_CHAIN_NAME=Jibchain Stack L2
# separate multiple values with commas; no spaces. single value with no commas is fine.
VITE_L2_RPC_URLS=https://rpc.hera.jbcha.in
# URL of the block explorer for the "L2" (rollup) chain
VITE_L2_EXPLORER_URL=https://www.hera.jbcha.in
# The address of the output oracle contract on the "L2" (rollup) chain
VITE_L2_ICON_URL=https://s2.coinmarketcap.com/static/img/coins/200x200/1027.png
# Background color for the icon of the "L2" (rollup) chain
VITE_L2_ICON_BACKGROUND_COLOR="#000"

# The chain's logo for the bridge UI
VITE_BRIDGE_LOGO_URL=https://avatars.githubusercontent.com/u/121443205?s=200&v=4
# The primary accent color for the bridge UI
VITE_BRIDGE_ACCENT_COLOR="#FF0000"
# Optional dark mode accent color, defaults to the primary accent color
VITE_BRIDGE_ACCENT_COLOR_DARK="#FF0000"
# The foreground color for the primary accent color
VITE_BRIDGE_ACCENT_COLOR_FOREGROUND="#FFFFFF"
# Optional dark mode accent color foreground, defaults to the primary accent color foreground
VITE_BRIDGE_ACCENT_COLOR_FOREGROUND_DARK="#FFFFFF"

# WalletConnect Project ID
VITE_WALLET_CONNECT_PROJECT_ID=380c789859ce659c8b3520635f18ca61
```

**Comment by mrmemes-eth** [comment] 2024-05-31 14:06
I have a couple of stumbling blocks to being able to test this:

1. 88991 doesn't [correspond to any known chain](https://chainlist.org/?search=88991&testnets=true)
2. I don't have a balance for the custom gas token, so I would see the same error as you (in my case, it would be accurate)

I don't think the current system will allow you to specify a parent chain that isn't already known to `viem`, so I don't think we can get past issue number 1 above without modifications. I assume you're creating a custom config for this chain in code?

**Comment by nidz-the-fact** [comment] 2024-05-31 14:48
> I have a couple of stumbling blocks to being able to test this:
> 
> 1. 88991 doesn't [correspond to any known chain](https://chainlist.org/?search=88991&testnets=true)
> 2. I don't have a balance for the custom gas token, so I would see the same error as you (in my case, it would be accurate)
> 
> I don't think the current system will allow you to specify a parent chain that isn't already known to `viem`, so I don't think we can get past issue number 1 above without modifications. I assume you're creating a custom config for this chain in code?

**Thank you** for the information. **Thank you once again** 👍

**Comment by mrmemes-eth** [comment] 2024-05-31 14:57
> **Thank you** for the information. **Thank you once again** 👍

Happy to help. If you think this resolves your issue, please do close it. It's also fine to leave this open if you need some time to investigate for a response.

**Closed as completed** 2024-05-31 18:26 UTC
